{
 "title": "Flow Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "TopNumber", "label": "Top values", "query": "1,2,3,4,5,10,20,30,40,50" },
   { "name": "FilterIPRanges", "label": "Filter IP ranges", "query": "Yes,No" },
   {
    "name": "IPranges",
    "label": "IP ranges",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Flow Count",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "// Variables\r\nlet IPrangesStr = '${IPranges}';\r\nlet IPrangesDyn = parse_json(IPrangesStr);\r\n// Query\r\nNTANetAnalytics\r\n| where isnotempty(DestPublicIps) or isnotempty(SrcPublicIps)\r\n| project SrcIp, SrcPublicIps, DestIp, DestPublicIps\r\n// Standard format for DestPublicIp\r\n| extend DestPublicIpsList = split(DestPublicIps, ' ')\r\n| mv-expand DestPublicIpsList\r\n| extend DestPublicIp = tostring(split(DestPublicIpsList, '|')[0])\r\n// Standard format for SrcPublicIp\r\n| extend SrcPublicIpsList = split(SrcPublicIps, ' ')\r\n| mv-expand SrcPublicIpsList\r\n| extend SrcPublicIp = tostring(split(SrcPublicIpsList, '|')[0])\r\n// Filter by service tag if required0\r\n| extend FilterIPRangesBool = \"$FilterIPRanges\"\r\n| where (FilterIPRangesBool == \"No\") or ipv4_is_in_any_range(SrcPublicIp, IPrangesDyn) or ipv4_is_in_any_range(DestPublicIp, IPrangesDyn)\r\n// Enrich with location for src and dst\r\n| lookup kind=leftouter NTAIpDetails on $left.DestPublicIp==$right.Ip\r\n| lookup kind=leftouter NTAIpDetails on $left.SrcPublicIp==$right.Ip\r\n| extend Direction = iff(isempty(SrcIp), 'Inbound', 'Outbound')\r\n// Consolidate Location\r\n| extend country_code = iff(isnotempty(Location), Location, Location1) | project-away Location1\r\n// Summarize by country\r\n| where isnotempty(country_code)\r\n| summarize FlowCount=count() by country_code",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Flows per threat type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "NTAIpDetails\r\n| where $__timeFilter(TimeGenerated)\r\n| where FlowType contains \"Malicious\"\r\n| summarize count() by ThreatType",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Transferred bytes of top $TopNumber source subnets",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "// Variables\r\nlet IPrangesStr = '${IPranges}';\r\nlet IPrangesDyn = parse_json(IPrangesStr);\r\n// Query\r\nNTANetAnalytics\r\n| where $__timeFilter(TimeGenerated)\r\n// Consolidate destip and destpublicips\r\n| extend DestPublicIpsList = split(DestPublicIps, ' ')\r\n| mv-expand DestPublicIpsList\r\n| extend DestPublicIp = split(DestPublicIpsList, '|')[0]\r\n| where isnotempty(DestIp) or isnotempty(DestPublicIp)\r\n| extend DestIp = iff(isnotempty(DestIp), DestIp, DestPublicIp)\r\n// Filter by service tag if required0\r\n| extend FilterIPRangesBool = \"$FilterIPRanges\"\r\n| where (FilterIPRangesBool == \"No\") or ipv4_is_in_any_range(DestIp, IPrangesDyn)\r\n// Main query\r\n| where isnotempty(SrcSubnet) \r\n| project Bytes=BytesDestToSrc+BytesSrcToDest, SrcSubnet\r\n| summarize TotalBytes=sum(Bytes) by SrcSubnet\r\n| top $TopNumber by TotalBytes\r\n",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Transferred bytes by applications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 15 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "// Variables\r\nlet IPrangesStr = '${IPranges}';\r\nlet IPrangesDyn = parse_json(IPrangesStr);\r\n// Query\r\nNTANetAnalytics\r\n| where SubType == \"FlowLog\"\r\n| where FlowStatus == \"Allowed\"\r\n// Consolidate destip and destpublicips\r\n| extend DestPublicIpsList = split(DestPublicIps, ' ')\r\n| mv-expand DestPublicIpsList\r\n| extend DestPublicIp = split(DestPublicIpsList, '|')[0]\r\n| where isnotempty(DestIp) or isnotempty(DestPublicIp)\r\n| extend DestIp = iff(isnotempty(DestIp), DestIp, DestPublicIp)\r\n// Filter by service tag if required0\r\n| extend FilterIPRangesBool = \"$FilterIPRanges\"\r\n| where (FilterIPRangesBool == \"No\") or ipv4_is_in_any_range(DestIp, IPrangesDyn)\r\n// Main query\r\n| summarize BytesSrc2Dst=sum(BytesSrcToDest), BytesDst2Src=sum(BytesDestToSrc) by DestPort=tostring(DestPort), bin(TimeGenerated, 30m)\r\n",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Transferred bytes by top $TopNumber Apps",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "// Variables\r\nlet IPrangesStr = '${IPranges}';\r\nlet IPrangesDyn = parse_json(IPrangesStr);\r\n// Query\r\nNTANetAnalytics\r\n| where $__timeFilter(TimeGenerated)\r\n| where SubType == \"FlowLog\"\r\n| where FlowStatus == \"Allowed\"\r\n// Consolidate destip and destpublicips\r\n| extend DestPublicIpsList = split(DestPublicIps, ' ')\r\n| mv-expand DestPublicIpsList\r\n| extend DestPublicIp = split(DestPublicIpsList, '|')[0]\r\n| where isnotempty(DestIp) or isnotempty(DestPublicIp)\r\n| extend DestIp = iff(isnotempty(DestIp), DestIp, DestPublicIp)\r\n// Filter by service tag if required0\r\n| extend FilterIPRangesBool = \"$FilterIPRanges\"\r\n| where (FilterIPRangesBool == \"No\") or ipv4_is_in_any_range(DestIp, IPrangesDyn)\r\n// Main query\r\n| project TotalBytes=BytesSrcToDest+BytesDestToSrc, Application=strcat(L4Protocol, tostring(DestPort))\r\n| summarize TotalBytes=sum(TotalBytes) by Application\r\n| top $TopNumber by TotalBytes\r\n",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Transferred bytes for top $TopNumber VMs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 22 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let IPrangesStr = '${IPranges}';\r\nlet IPrangesDyn = parse_json(IPrangesStr);\r\n//let IPranges = parse_json($IPranges);\r\nNTANetAnalytics\r\n| where $__timeFilter(TimeGenerated)\r\n// Consolidate destip and destpublicips\r\n| extend DestPublicIpsList = split(DestPublicIps, ' ')\r\n| mv-expand DestPublicIpsList\r\n| extend DestPublicIp = split(DestPublicIpsList, '|')[0]\r\n| where isnotempty(DestIp) or isnotempty(DestPublicIp)\r\n| extend DestIp = iff(isnotempty(DestIp), DestIp, DestPublicIp)\r\n| extend FilterIPRangesBool = \"$FilterIPRanges\"\r\n// Filter by service tag if required0\r\n| where (FilterIPRangesBool == \"No\") or ipv4_is_in_any_range(DestIp, IPrangesDyn)\r\n// Main query\r\n| project SrcVm, TotalBytes=BytesDestToSrc+BytesSrcToDest\r\n| where isnotempty(SrcVm)\r\n| summarize TotalBytes=sum(TotalBytes) by SrcVm\r\n| top $TopNumber by TotalBytes",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Flows per region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "// Variables\r\nlet IPrangesStr = '${IPranges}';\r\nlet IPrangesDyn = parse_json(IPrangesStr);\r\n// Query\r\nNTANetAnalytics\r\n| where $__timeFilter(TimeGenerated)\r\n// Consolidate destip and destpublicips\r\n| extend DestPublicIpsList = split(DestPublicIps, ' ')\r\n| mv-expand DestPublicIpsList\r\n| extend DestPublicIp = split(DestPublicIpsList, '|')[0]\r\n| where isnotempty(DestIp) or isnotempty(DestPublicIp)\r\n| extend DestIp = iff(isnotempty(DestIp), DestIp, DestPublicIp)\r\n// Filter by service tag if required0\r\n| extend FilterIPRangesBool = \"$FilterIPRanges\"\r\n| where (FilterIPRangesBool == \"No\") or ipv4_is_in_any_range(DestIp, IPrangesDyn)\r\n// Main query\r\n| mvexpand Region = pack_array(SrcRegion, DestRegion)\r\n| summarize num = count() by tostring(Region)\r\n| where isnotempty(Region)",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Flows to malicious endpoints by subnets",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 30 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let MAliciousIps = NTAIpDetails \r\n| where FlowType == \"MaliciousFlow\" \r\n| where $__timeFilter(TimeGenerated)\r\n| project-away TimeGenerated, SubType, FaSchemaVersion, FlowIntervalEndTime, FlowIntervalStartTime, FlowType, Type \r\n| distinct *; \r\nlet MaliciousFlows =  NTANetAnalytics \r\n| where $__timeFilter(TimeGenerated)\r\n| where SubType == \"FlowLog\" and FlowType == \"MaliciousFlow\" \r\n| project SrcIp, DestIp, SrcSubnet, DestSubnet; \r\nlet SrcMalicious = MaliciousFlows \r\n| lookup kind=inner MAliciousIps on $left.SrcIp == $right.Ip \r\n| project Subnet = DestSubnet, MaliciousIp = SrcIp, PublicIpDetails, ThreatType, DnsDomain, ThreatDescription, Location, Url; \r\nlet DestMalicious = MaliciousFlows \r\n| lookup kind=inner MAliciousIps on $left.DestIp == $right.Ip \r\n| project Subnet = SrcSubnet, MaliciousIp = DestIp,  PublicIpDetails, ThreatType, DnsDomain, ThreatDescription, Location, Url; \r\nSrcMalicious \r\n| union DestMalicious\r\n| where Subnet != \"\"\r\n| summarize counterValue = count() by Subnet, MaliciousIp,  PublicIpDetails, ThreatType, Location, Url",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Traffic to malicious endpoints by IP addresses",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 37 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let MaliciousIps = NTAIpDetails \r\n    | where $__timeFilter(TimeGenerated)\r\n    | where FlowType == \"MaliciousFlow\" \r\n    | project-away\r\n        TimeGenerated,\r\n        SubType,\r\n        FaSchemaVersion,\r\n        FlowIntervalEndTime,\r\n        FlowIntervalStartTime,\r\n        FlowType,\r\n        Type \r\n    | distinct *;\r\nlet MaliciousFlows =  NTANetAnalytics \r\n    | where $__timeFilter(TimeGenerated)\r\n    | where SubType == \"FlowLog\" and FlowType == \"MaliciousFlow\" \r\n    | where iff(\"'*'\" == \"'*'\", true, (SrcSubscription in~ ('*') or DestSubscription in~ ('*')))\r\n    | project \r\n        SrcIp,\r\n        DestIp,\r\n        SrcVm,\r\n        DestVm,\r\n        SrcSubscription,\r\n        DestSubscription; \r\nlet SrcMalicious = MaliciousFlows \r\n    | lookup kind=inner MaliciousIps on $left.SrcIp == $right.Ip\r\n    | extend CompromisedVM = iff(isnotempty(DestVm), strcat(\"/subscriptions/\", DestSubscription, \"/resourceGroups/\", tostring(split(DestVm, \"/\")[0]), \"/providers/Microsoft.Compute/virtualMachines/\", tostring(split(DestVm, \"/\")[1])), '')\r\n    | project\r\n        CompromisedIp = strcat('🖥️', DestIp),\r\n        MaliciousIp = strcat('🌐 ', SrcIp),\r\n        CompromisedVM,\r\n        PublicIpDetails,\r\n        ThreatType,\r\n        DnsDomain,\r\n        ThreatDescription,\r\n        Location,\r\n        Url;\r\nlet DestMalicious = MaliciousFlows \r\n    | lookup kind=inner MaliciousIps on $left.DestIp == $right.Ip \r\n    | extend CompromisedVM = iff(isnotempty(SrcVm), strcat(\"/subscriptions/\", SrcSubscription, \"/resourceGroups/\", tostring(split(SrcVm, \"/\")[0]), \"/providers/Microsoft.Compute/virtualMachines/\", tostring(split(SrcVm, \"/\")[1])), '')\r\n    | project\r\n        CompromisedIp = strcat('🖥️ ', SrcIp),\r\n        MaliciousIp = strcat('🌐 ', DestIp),\r\n        CompromisedVM,\r\n        PublicIpDetails,\r\n        ThreatType,\r\n        DnsDomain,\r\n        ThreatDescription,\r\n        Location,\r\n        Url; \r\nSrcMalicious \r\n| union DestMalicious",
      "resources": [
       "/subscriptions/3e78e84b-6750-44b9-9d57-d9bba935237a/resourceGroups/flowlogs/providers/Microsoft.OperationalInsights/workspaces/log11797"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}